version: '3.8'

services:
  content:
    container_name: book_content
    build:
      context: .
      dockerfile: content.dockerfile
    image: phaustin/problem_solving_content:sep10
    volumes:
      - type: volume
        source: problem-solving-notebooks
        target: /srv/problem_solving_notebooks
  
  jupyterhub:
    build: hub_image
    image: phaustin/jupyterhub:textbook
    container_name: jupyterhub
    depends_on: [notebook]
    ports:
      - "8500:8000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - textbook_network

  notebook:
    build: notebook_image
    image: phaustin/notebook:textbook
    container_name: notebook
    depends_on: [content]
    volumes:
      - problem-solving-notebooks:/srv/problem_solving_notebooks

    # command: jupyterhub-singleuser

# set the network name
# this needs to be matched in jupyterhub_config.py by:
# c.DockerSpawner.network_name = 'textbook_network'
networks:
    textbook_network:
      driver: bridge
      name: textbook_network

volumes:
  problem-solving-notebooks:
    name: problem-solving-notebooks


