#######################################################################################
# Book settings
title: "PSWP"
logo: images/logo.png
author: Peter D. Kazarinoff, PhD
email: peter.kazarinoff@pcc.edu
description: >- # this means to ignore newlines until "baseurl:"
  A jupyter-book port of "Problem Solving with Python"
  [https://www.amazon.com/dp/1693405415](https://www.amazon.com/dp/1693405415)

execute:
  execute_notebooks: cache

exclude_patterns: ["*ipynb"]

repository:
  url: https://github.com/phaustin/Problem-Solving-with-Python-37-Edition.git
  branch: jb
  path_to_book: notebooks

launch_buttons:
  notebook_interface: "classic" # The interface interactive links will activate ["classic", "jupyterlab"]
  jupyterhub_url: http://node07.eos.ubc.ca:8000
  
html:
  home_page_in_navbar: true
  baseurl: http://node07.eos.ubc.ca:8080

